#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Mar 10 11:08:00 PST 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sim_behav -key {Behavioral:sim_1:Functional:sim} -tclbatch sim.tcl -view /home/brianm/Documents/Repos/CPE233Labs/HW8_CSR/sim_behav.wcfg -log simulate.log"
xsim sim_behav -key {Behavioral:sim_1:Functional:sim} -tclbatch sim.tcl -view /home/brianm/Documents/Repos/CPE233Labs/HW8_CSR/sim_behav.wcfg -log simulate.log

