#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 22 08:49:56 PST 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Otter_MCU_behav -key {Behavioral:sim_1:Functional:Otter_MCU} -tclbatch Otter_MCU.tcl -log simulate.log"
xsim Otter_MCU_behav -key {Behavioral:sim_1:Functional:Otter_MCU} -tclbatch Otter_MCU.tcl -log simulate.log

